services:
  - type: web
    name: dndbrand-server
    env: node
    plan: free
    buildCommand: >
      cd server && 
      npm install --legacy-peer-deps && 
      npm install node-cache winston --legacy-peer-deps && 
      npm run postinstall && 
      cd .. && 
      node apply-fixes.js &&
      node verify-routes.js || echo "Warning: Issues detected after fixes, but continuing with deployment"
    startCommand: cd server && node production-server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: LOG_LEVEL
        value: info
    healthCheckPath: /api/health
    autoDeploy: true

  - type: static
    name: dndbrand-frontend
    buildCommand: echo "Static site ready"
    staticPublishPath: ./public
    # Add routes configuration for SPA-like navigation
    routes:
      - type: rewrite
        source: /shop
        destination: /html/shop.html
      - type: rewrite
        source: /about
        destination: /html/about.html
      - type: rewrite
        source: /contact
        destination: /html/contact.html
      - type: rewrite
        source: /cart
        destination: /html/cart.html  
      - type: rewrite
        source: /checkout
        destination: /html/checkout.html
      - type: rewrite
        source: /account
        destination: /html/account.html
      - type: rewrite
        source: /search
        destination: /html/search.html
      - type: rewrite
        source: /collections
        destination: /html/collections.html
      - type: rewrite
        source: /shipping
        destination: /html/shipping.html
      - type: rewrite
        source: /returns
        destination: /html/returns.html
      - type: rewrite
        source: /faq
        destination: /html/faq.html
      - type: rewrite
        source: /sustainability
        destination: /html/sustainability.html  
      - type: rewrite
        source: /careers
        destination: /html/careers.html
      - type: rewrite
        source: /privacy
        destination: /html/privacy.html
      - type: rewrite
        source: /product
        destination: /html/product.html
      # Catch all other routes to 404 page
      - type: rewrite
        source: /*
        destination: /html/404.html 